version: "3"
services:
  app:
    build: ./docker/app
    volumes:
      - ./:/var/www/html
      - ./docker/app/php.ini:/usr/local/etc/php/php.ini
    command: php artisan serve --host 0.0.0.0
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/init:/docker-entrypoint-initdb.d
  db-test:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./docker/db-test/data:/var/lib/mysql
      - ./docker/db-test/init:/docker-entrypoint-initdb.d
